port    3389
server  172.27.213.0 255.255.255.128
proto   tcp
dev     tun

ca      /data/openvpn/conf/wd.server.openvpn/ca.openvpn.vpn.crt
cert    /data/openvpn/conf/wd.server.openvpn/wd.server.openvpn.crt
# 私钥需要保密。
key     /data/openvpn/conf/wd.server.openvpn/wd.server.openvpn.key
# Diffie-Hellman parameters 需要保密。
dh      /data/openvpn/conf/wd.server.openvpn/wd.server.openvpn.dh

status                  /data/openvpn/log/wd.server.openvpn.status.txt
log                     /data/openvpn/log/wd.server.openvpn.txt
log-append              /data/openvpn/log/wd.server.openvpn.txt
ifconfig-pool-persist   /data/openvpn/tmp/wd.server.openvpn.ipp

client-to-client
comp-lzo
verb                    6
user                    nobody
group                   nobody
client-config-dir       /data/openvpn/conf/wd.server.openvpn/ccd

push "route 172.27.213.0 255.255.255.128"
push "route 10.254.157.0 255.255.255.0"
push "route 10.254.160.0 255.255.255.0"
push "route 172.24.133.0 255.255.255.0"
push "route 172.24.138.0 255.255.255.0"
push "route 172.27.157.0 255.255.255.0"
push "route 172.254.157.0 255.255.255.0"
push "route 192.168.9.0 255.255.255.0"
push "route 192.168.202.0 255.255.255.0"