client
remote	        qd.ppno.net 7794
proto           tcp-client
dev             tun

ca              /data/etc/openvpn/qd.research.virtual/ca.openvpn.vpn.crt
cert            /data/etc/openvpn/qd.research.virtual/qd.research.virtual.crt
key             /data/etc/openvpn/qd.research.virtual/qd.research.virtual.key

status          /data/var/log/openvpn/qd.research.virtual/qd.research.virtual.status.txt
log             /data/var/log/openvpn/qd.research.virtual/qd.research.virtual.txt
log-append      /data/var/log/openvpn/qd.research.virtual/qd.research.virtual.txt

persist-key
persist-tun
comp-lzo
remote-cert-tls server
verb		    9

user            nobody
group           nogroup

tls-cipher      DEFAULT:@SECLEVEL=0