client
remote	        qd.ppno.net 7794
proto           tcp-client
dev             tun

# 链接：/usr/local/etc/openvpn -> /data/etc/openvpn。
ca              /usr/local/etc/openvpn/qd.asux.home/ca.openvpn.vpn.crt
cert            /usr/local/etc/openvpn/qd.asux.home/qd.asux.home.crt
# 私钥需要保密。
key             /usr/local/etc/openvpn/qd.asux.home/qd.asux.home.key

# 链接：/usr/local/var/log/openvpn -> /data/var/log/openvpn。
status          /usr/local/var/log/openvpn/qd.asux.home/qd.asux.home.status.txt
log             /usr/local/var/log/openvpn/qd.asux.home/qd.asux.home.txt
log-append      /usr/local/var/log/openvpn/qd.asux.home/qd.asux.home.txt

persist-key
persist-tun
comp-lzo
remote-cert-tls server
verb		    9

user            nobody
group           nobody

tls-cipher      DEFAULT:@SECLEVEL=0