port    7794
server  172.27.53.0 255.255.255.128
proto   tcp
dev     tun

ca      /data/openvpn/conf/qd.server.openvpn/ca.openvpn.vpn.crt
cert    /data/openvpn/conf/qd.server.openvpn/qd.server.openvpn.crt
# 私钥需要保密。
key     /data/openvpn/conf/qd.server.openvpn/qd.server.openvpn.key
# Diffie-Hellman parameters 需要保密。
dh      /data/openvpn/conf/qd.server.openvpn/qd.server.openvpn.dh

tls-version-min         1.0
tls-cipher              DEFAULT:@SECLEVEL=0

status                  /data/openvpn/log/qd.server.openvpn.status.txt
log                     /data/openvpn/log/qd.server.openvpn.txt
log-append              /data/openvpn/log/qd.server.openvpn.txt
ifconfig-pool-persist   /data/openvpn/tmp/qd.server.openvpn.ipp

client-to-client
comp-lzo
verb                    4
user                    nobody
group                   nobody
client-config-dir       /data/openvpn/conf/qd.server.openvpn/ccd

push "route 172.27.53.0 255.255.255.128"
